<?php

$config['main_menu'] = array(
		(object)array(
			'name'=>'system',
			'title'=>'Sistema',
			'items'=>array(
				(object)array(
					'name'=>'currencies',
					'title'=>'Monedas',
				),
				(object)array(
					'name'=>'countries',
					'title'=>'Paises',
				),
				(object)array(
					'name'=>'cities',
					'title'=>'Ciudades',
				),
				(object)array(
					'name'=>'periods',
					'title'=>'Periodos',
				),
				(object)array(
					'name'=>'users_management',
					'title'=>'Usuarios',
				),
			),
		),
		(object)array(
			'name'=>'warehouse',
			'title'=>'Bodegas',
			'items'=>array(
				(object)array(
					'name'=>'catalog',
					'title'=>'Listado',
				),
				(object)array(
					'name'=>'transfer',
					'title'=>'Transferencias',
				),
			),
		),
		(object)array(
			'name'=>'article',
			'title'=>'Articulos',
			'items'=>array(
				(object)array(
					'name'=>'catalog',
					'title'=>'Listado',
				),
				(object)array(
					'name'=>'category',
					'title'=>'Categor&iacute;as',
				),
			),
		),
		(object)array(
			'name'=>'point_of_sale',
			'title'=>'Punto de Venta',
			'items'=>array(
				(object)array(
					'name'=>'rendition',
					'title'=>'Listado de Rendiciones',
				),
			),
		),
		(object)array(
			'name'=>'expense',
			'title'=>'Gastos',
			'items'=>array(
				(object)array(
					'name'=>'catalog',
					'title'=>'Listado',
				),
				(object)array(
					'name'=>'provider',
					'title'=>'Proveedores',
				),
				(object)array(
					'name'=>'type',
					'title'=>'Tipos de gasto',
				),
			),
		),
		(object)array(
			'name'=>'utilidades',
			'title'=>'Utilidades',
			'items'=>array(
			),
		),
		(object)array(
			'name'=>'reports',
			'title'=>'Reportes',
			'items'=>array(
				(object)array(
					'name'=>'general_stock',
					'title'=>'Existencias',
				),
				(object)array(
					'name'=>'article_sales',
					'title'=>'Ventas por articulo',
				),
				(object)array(
					'name'=>'warehouse_sales',
					'title'=>'Ventas por punto de venta',
				),
				(object)array(
					'name'=>'warehouse_commisions',
					'title'=>'Comisiones por punto de venta',
				),
				(object)array(
					'name'=>'general',
					'title'=>'Resumen General',
				),
			),
		),
	);